GET http://localhost:9999/clientes/1/extrato


###
GET http://localhost:8081/clientes/6/extrato

###
GET http://localhost:8080/clientes/3/extrato

###
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "tipo": "c",
  "valor": 200,
  "descricao": "devolve"
}

###
POST http://localhost:9999/clientes/3/transacoes
Content-Type: application/json

{
  "tipo": "x",
  "valor": 1,
  "descricao": "devolve"
}

###
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "tipo": "c",
  "valor": 1,
  "descricao": "123456789 e mais um pouco"
}

###
POST http://localhost:9999/clientes/3/transacoes
Content-Type: application/json

{
  "tipo": "c",
  "valor": 1,
  "descricao": ""
}

###
POST http://localhost:9999/clientes/3/transacoes
Content-Type: application/json

{
  "tipo": "c",
  "valor": 1,
  "descricao": null
}