server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: r2dbc:${DB_KIND:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rinha}
    username: rinha
    password: rinha
    pool:
      enabled: true
      initial-size: 15
      max-size: 15
      max-idle-time: 30m
  main:
    banner-mode: off

